//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
<<<<<<< HEAD
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EADProj {
    
    
    public partial class main {
=======
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EADProj
{


    public partial class main
    {
>>>>>>> Yappy
    }
}
